systemLog:
   destination: file
   path: "C:/walkner-tp/data/logs/mongodb.log"
   logAppend: true
storage:
   journal:
      enabled: true
   dbPath: "C:/walkner-tp/data/mongodb"
   directoryPerDB: true
net:
   bindIp: 127.0.0.1
   port: 27017
